apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-session-resources"
spec:
  title: "Session Resources"
  description: "Overview of creating per session resources."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-session-resources-files:$(workshop_version)
  workshop:
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-session-resources-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      files:
        enabled: true
