apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-shared-resources"
spec:
  title: "Shared Resources"
  description: "Overview of pre-creating shared resources."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-shared-resources-files:$(workshop_version)
  workshop:
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-shared-resources-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: false
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
      files:
        enabled: true
