apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-ingress-proxy"
spec:
  title: "Ingress Proxy"
  description: "Overview of adding ingresses for local processes."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-ingress-proxy-files:$(workshop_version)
  workshop:
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-ingress-proxy-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
