apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-slide-presentations"
spec:
  title: "Slide Presentations"
  description: "Overview of integrating slide presentations."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-slide-presentations-files:$(workshop_version)
  workshop:
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-slide-presentations-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      slides:
        enabled: true
        reveal.js:
          version: 3.X
      files:
        enabled: true
