apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-examiner-scripts"
spec:
  title: "Examiner Scripts"
  description: "Overview of using self check examinations."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-examiner-scripts-files:$(workshop_version)
  workshop:
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-examiner-scripts-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
  session:
    namespaces:
      security:
        policy: baseline
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      files:
        enabled: true
      examiner:
        enabled: true
